name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'
      - run: npm install

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        env:
            ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
        run: forge build --hh
      - run: forge test --fork-url https://eth-mainnet.alchemyapi.io/v2/${{ env.ALCHEMY_KEY }} -vvvvv -c contracts --hh
